package com.iwop.rastreadormovil;

public class CambiosVersiones {
/*
 * VERSION 12.2 (SE PRETENDE CORREGIR ERROR DE CALCULO DE CARRERAS- INGRESA MEDIA CARRERA AL FINAL
 *   Y LA DETECCION DE LA PARADA CERCANA YA QUE DETECTABA PARADAS DE OTROS RAMALES QUE ESTABAN CERCA.
 * 
 * - CAMBIO DE RANGO DE DETECCION DE PARADA CERCADA DE 100MTS A 25 MTS
 * - CAMBIO DE METODO PARA DETECTAR PARADAS, SE PONE QUE COMIENCE LA ASYNCTASK CUANDO HAYAN PASADO 4 SEG O CUANDO LA VELOCIDAD
 * 	 BAJE A 20 KM/H
 * - CAMBIO DE SUMA DE MEDIAS CARRERAS AHORA AL MOMENTO DE LLEGAR AL SENTIDO 1 (TERMINAL) SE LE SUMA 1 CARRERA
 *   Y GUARDA EL ID DEL INSERT QUE HIZO. AL MOMENTO DE LLEGAR AL SENTIDO 2 NO CUENTA CARRERA PERO HACE UN UPDATE DESDE EL INSERT
 *   DEL CAMBIO DE SENTIDO PREVIO HASTA LA FECHA ACTUAL Y ESTABLECE CARRERAS=CARRERAS-0.5 ES DECIR SE CUENTA LA MEDIA CARRERA
 *   ANTICIPADAMENTE Y LUEGO SE ACTUALIZA. ESTO ESTA A PRUEBA.
 *   
 * VERSION 12.3 (SE PRETENDE CORREGIR ERROR QUE ESTA DANDO DE TIMEOUT EN MODULOSQL.EJECUTAR
 * 
 * - SE CAMBIA TIMEOUT DEL GET DE LA ASYNCTASK A 25 s.
 * - SE BAJA EL TIMEOUT DEL CONEXION.VALID() DENTRO DE LA ASYNCTASK A 15 s CON EL FIN DE TENER 10s PARA ESTABLECER UNA NUEVA CONEXION
 *   Y REALIZAR EL INSERT.
 * 
 * 
 * 
 * 
 * 
 * 
 * */
}
